#!/bin/zsh
export ZDOTDIR="${ZDOTDIR:-$HOME/.config/zsh}"
[[ -r $ZDOTDIR/.zshenv ]] && . $ZDOTDIR/.zshenv

# vscode integration
if [[ "$TERM_PROGRAM" == "vscode" ]]; then
  ZDOTDIR=$HOME/.config/zsh
  . "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-rc.zsh"
fi