[tools]
"cargo:cargo-nextest" = "latest"
go = "1.24.0"
node = "22"
python = "latest"
rust = "latest"
ubi = "latest"
"ubi:bytecodealliance/wasm-tools" = "latest"
wasmtime = "latest"

[settings]
experimental = true
