#!/bin/zsh

# https://github.com/g-plane/pnpm-shell-completion

local comp=$(antidote path g-plane/pnpm-shell-completion)/pnpm-shell-completion
local installer=$(antidote path g-plane/pnpm-shell-completion)/install.zsh

if [[ -e $installer ]] && [[ ! -e $comp ]]; then
  $installer
fi