#!/bin/zsh

# https://github.com/g-plane/zsh-yarn-autocompletions

local comp=$(antidote path g-plane/zsh-yarn-autocompletions)/zsh-yarn-autocompletions
local installer=$(antidote path g-plane/zsh-yarn-autocompletions)/install.zsh

if [[ -e $installer ]] && [[ ! -e $comp ]]; then
  $installer
fi