#!/bin/zsh
# shellcheck disable=SC1071

## Anti-dot
# This comes at the start so that all the other scripts that might depend on
# them are configured first.
source "${ZDOTDIR:-$HOME}/lib/000-antidot.zsh"

## Setup
source "${ZDOTDIR:-$HOME}/lib/010-setup.zsh"

## Plugins (pre)
source "${ZDOTDIR:-$HOME}/lib/050-plugins-pre.zsh"

## Config
source "${ZDOTDIR:-$HOME}/lib/200-config.zsh"

## Aliases
source "${ZDOTDIR:-$HOME}/lib/210-aliases.zsh"

## Languages
source "${ZDOTDIR:-$HOME}/lib/220-languages.zsh"

## Completions
source "${ZDOTDIR:-$HOME}/lib/500-completions.zsh"

## Secrets
source "${ZDOTDIR:-$HOME}/lib/700-secrets.zsh"

## Plugins (post)
source "${ZDOTDIR:-$HOME}/lib/900-plugins-post.zsh"
