#!/bin/zsh
#
# .zshenv: Zsh environment file, loaded always.
#

export ZDOTDIR=${ZDOTDIR:-$HOME/.config/zsh}

# enable vscode shell integration
if [[ "$TERM_PROGRAM" == "vscode" ]]; then
  export ZDOTDIR="${HOME}/.config/zsh"
  export VSCODE_SUGGEST=1
  . "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-rc.zsh"
fi
