#!/bin/zsh
#
# .zshenv: Zsh environment file, loaded always.
#

export ZDOTDIR=${ZDOTDIR:-$HOME/.config/zsh}

# enable vscode shell integration
if [[ "$TERM_PROGRAM" == "vscode" ]]; then
  export ZDOTDIR="${HOME}/.config/zsh"
  export VSCODE_SUGGEST=1
  . "$(code --locate-shell-integration-path zsh)"
fi
