#!/bin/zsh
# shellcheck disable=SC1071

echo "Loading zsh configuration..."
echo $ZSH
echo "---"

## Setup
# These are the first things that should be loaded. This is where we set up the
# environment and load anything that is likely to be needed by other modules.
source "${ZDOTDIR}/lib/100-setup.zsh"

## Modules
# This isn't really a module system, but rather a way to load different parts of
# the configuration in a more organized way.
# It loads each *.zsh file in the `zmodules` directory in order.
source "${ZDOTDIR}/lib/500-modules.zsh"

## Post config setup
# Anything that must be loaded after the modules are loaded should be loaded
# here. Useful for stuff that might happen in the background and shouldn't block
# the shell from starting.
source "${ZDOTDIR}/lib/900-post.zsh"
