#!/bin/zsh
# shellcheck disable=SC1071

## Anti-dot
# This comes at the start so that all the other scripts that might depend on
# them are configured first.
source "${ZDOTDIR:-$HOME}/lib/antidot.zsh"

## Setup
source "${ZDOTDIR:-$HOME}/lib/setup.zsh"

## Config
source "${ZDOTDIR:-$HOME}/lib/config.zsh"

## Aliases
source "${ZDOTDIR:-$HOME}/lib/aliases.zsh"

## Languages
source "${ZDOTDIR:-$HOME}/lib/languages.zsh"

## Completions
source "${ZDOTDIR:-$HOME}/lib/completions.zsh"

## Secrets
source "${ZDOTDIR:-$HOME}/lib/secrets.zsh"
