#!/bin/sh

## init
"$ZDOTDIR"/plugins/starship-ftl
mattmc3/zephyr path:plugins/environment
mattmc3/zephyr path:plugins/homebrew
mattmc3/zephyr path:plugins/zfunctions
"$ZDOTDIR"/plugins/xdg

# themes
mattmc3/zephyr path:plugins/prompt
"$ZDOTDIR"/themes kind:fpath

## compinit helper
getantidote/use-omz

## config
mattmc3/zephyr path:plugins/color
mattmc3/zephyr path:plugins/completion
mattmc3/zephyr path:plugins/history

## macos
mattmc3/zephyr path:plugins/macos conditional:is-macos

## plugins
"$ZDOTDIR"/plugins/asdf
zsh-users/zsh-syntax-highlighting
zsh-users/zsh-autosuggestions
zsh-users/zsh-completions kind:fpath path:src
ajeetdsouza/zoxide
g-plane/pnpm-shell-completion kind:zsh post:post_pnpm_comp
romkatv/zsh-bench kind:path

## omz plugins
ohmyzsh/ohmyzsh path:plugins/direnv
ohmyzsh/ohmyzsh path:plugins/eza
ohmyzsh/ohmyzsh path:plugins/git
ohmyzsh/ohmyzsh path:plugins/gitfast
ohmyzsh/ohmyzsh path:plugins/sudo
ohmyzsh/ohmyzsh path:plugins/encode64
ohmyzsh/ohmyzsh path:plugins/extract
ohmyzsh/ohmyzsh path:plugins/command-not-found

## atuin
"$ZDOTDIR"/plugins/atuin