#:schema https://mise.jdx.dev/schema/mise.json

[settings.npm]
package_manager = "aube"

[tools]
node = "lts"
go = "latest"
ubi = "latest"
rust = "latest"
python = "latest"
fnox = "latest"

[tools.'http:pool']
version = "latest"
url = "https://downloads.poolside.ai/pool/v{{ version }}/pool-{{ os(macos='darwin') }}-{{ arch(x64='amd64') }}.tar.gz"
version_list_url = "https://downloads.poolside.ai/pool/pool-latest-version.txt"
rename_exe = "pool"
