#!/bin/bash
# Source: https://gist.github.com/mislav/e154d707db230dc882d7194ec85d79f6
#
# Dependencies: gh
#
set -e

cmd="$1"
if [ "erase" = "$cmd" ]; then
  cat - >/dev/null
  exit 0
fi
if [ "store" = "$cmd" ]; then
  cat - >/dev/null
  exit 0
fi
if [ "get" != "$cmd" ]; then
  exit 1
fi

host="$(cat -)"
host="${host#https://}"
host="${host%/}"
if [ "$host" != "ghcr.io" ] && [ "$host" != "docker.pkg.github.com" ]; then
  exit 1
fi

token="$(gh auth token)"
if [ -z "$token" ]; then
  exit 1
fi

gh auth status --active --hostname github.com --show-token --json hosts --jq '.hosts["github.com"][0] | {Username:.login,Secret:.token}'